sqlite:
  adapter: sqlite
  database: vendor/plugins/custom_attributes/spec/custom_attributes_plugin.sqlite.db

sqlite3:
  adapter: sqlite3
  database: vendor/plugins/custom_attributes/spec/custom_attributes_plugin.sqlite3.db

postgresql:
  adapter: postgresql
  username: postgres
  password: postgres
  database: custom_attributes_plugin_test
  min_messages: ERROR

mysql:
  adapter: mysql
  host: localhost
  username: root
  password:
  database: custom_attributes_plugin_test
